const SAVE_USER = 'SAVE_USER';
const SAVE_TOKEN = 'SAVE_TOKEN';
const SAVE_ID = 'SAVE_ID';
const POST_QUE = 'POST_QUE';
const GET_POSTS = 'GET_POSTS';
const SAVE_POSTS = 'SAVE_POSTS';

export {SAVE_TOKEN, SAVE_USER, SAVE_POSTS, SAVE_ID, POST_QUE, GET_POSTS};
